export enum PagesNamesEnum {
  DEFAULT = "",
  ABOUT_US = "about-us",
  BLOG = "blog",
  CANDIDATES = "candidates",
  CAREER_BLOG = "career-blog",
  COACHING = "coaching",
  COMPANIES = "companies",
  CONTACT_US = "contact-us",
  FAQ = "faq",
  JOBS = "jobs",
  LOGIN = "login",
  ONLINE_COURSE = "online-course",
  SALES = "sales",
  SERVICES = "services",
  LEGAL_NOTICE = "legal-notice",
  PRIVACY_POLICY = "privacy-policy",
  TERMS = "terms-and-conditions",
}
