export enum EPagesNames {
  DEFAULT = "candidates",
  ABOUT_US = "about-us",
  BLOG = "blog",
  CANDIDATES = "candidates",
  CAREER_BLOG = "career-blog",
  COACHING = "coaching",
  COMPANIES = "companies",
  CONTACT_US = "contact-us",
  FAQ = "faq",
  JOBS = "talent-pool",
  LOGIN = "login",
  ONLINE_COURSE = "online-course",
  SALES = "dream-job",
  SERVICES = "services",
  LEGAL_NOTICE = "legal-notice",
  PRIVACY_POLICY = "data-protection",
  TERMS = "terms-and-conditions",
  PRIVACY_APPLICANTS = "privacy-applicants",
  DATA_PRIVACY = "data-privacy",
}
